### ISSUE TITLE
Addon to regen custom world from backup folder

### ISSUE THREAD

**Issue by cancabron** [SBPrime/AsyncWorldEdit-Premium#5]
Hi, I'm looking for a plugin regeneration custom maps.

Perhaps your plugin can create an addon that seeks modified chunks and go regenerating in the background.

The plugin should exclude worldguard regions and factions. It would be helpful and many people who have servers factions would buy it.

When I say I do custom maps maps created from scratch. Using WorldPainter or another program.

The plugin should look in a folder with the original backup of the map.

If this were possible it would help in whatever it took.

Greetings and sorry for my English.

**Comment by SBPrime** [comment]
I'll defiantly add this to planed features. I can't give you any ETA but if you like we can talk and work out the details.

**Comment by cancabron** [comment]
This is my initial proposal setting. Administrators create a map will always have their original saved in a folder dedicated to the regeneration map.

The only plugin should look for chunks that have no factions or regions.

Then I set it up to do the background process agreed in the range of configuration time.

```
config:
    enabled-worlds: #List with all the worlds that can be regen
        - MyWorld
        - MyWorld2

    snapshot-directory: #Directory that contains every world folder
        - /home/myserver/backups/

    hook:   #Plugins that hooks
        Factions: true
        WorldGuard: true
        OtherPluginHook: true

    enable-command-use: true    #Command to start regen task using the console or admin permission command

    auto-task-every: 2d #Days to auto exectute the regen task; days(d), weeks(w), months(m)
```

-- Other features that would be amazing --

Replace some ores in a given radio. So players will not be marked with external programs where ores are located. Each time the map is regenerated obtain a different ores in the position they originally had.

Sorry for my english :cry:
